import Header from '@/components/header/header'
import './global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='flex flex-col' lang="en">
      <Header />
      {children}
      <div className='h-screen'>.</div>
      <Footer />
    </html>
  )
}
